#!/bin/bash

#git config user.email "mobile@andreboyce.com"
#git config --global user.name "Andre Boyce"
#rm -rf .git
#git init
#git add -A
#git commit -m "first commit"
#git branch -M main
#git remote set-url origin 'git@github.com:andreboyce/linux_shell.git'

MESSAGE=$1

if [ -z "$MESSAGE" ]
then
   MESSAGE="update";
else
   :
fi

# cp regex_tool_dev.html regex_tool.html
./dev/windows_launch;

git add -A
git commit -m "$MESSAGE"
git push -u origin main
